{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helpers.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ join "," .Values.ingress.hosts | quote }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    #
    ingress-dashboard/title: "[{{ .Release.Namespace }}] - {{ .Chart.Name }}"
    ingress-dashboard/description: {{ .Chart.Description }}; hosted in [{{ .Release.Namespace }}] cluster environment
    ingress-dashboard/logo-url: {{ .Values.ingress.bookEntry.logoUrl | quote }}
    ingress-dashboard/hide: {{ (not .Values.ingress.bookEntry.shown) | quote }}
    ingress-dashboard/assume-tls: "true" {{- /* always assume TLS since Cloudflare is fronting */}}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "helpers.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- range .Values.ingress.extraHosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "helpers.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}