{{- if eq .Values.secret.pierceflare.source "values" -}}
{{- if not .Values.secret.pierceflare.values.CLOUDFLARE_API_TOKEN }}
{{- fail "You must provide .Values.secret.pierceflare.values.CLOUDFLARE_API_TOKEN in values.yaml" }}
{{- end }}
{{- if not .Values.secret.pierceflare.values.SERVICE_AUTH_USERNAME }}
{{- fail "You must provide .Values.secret.pierceflare.values.SERVICE_AUTH_USERNAME in values.yaml" }}
{{- end }}
{{- if not .Values.secret.pierceflare.values.SERVICE_AUTH_PASSWORD }}
{{- fail "You must provide .Values.secret.pierceflare.values.SERVICE_AUTH_PASSWORD in values.yaml" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.pierceflare.secretName }}
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: {{ .Values.secret.pierceflare.values.CLOUDFLARE_API_TOKEN | quote }}
  SERVICE_AUTH_USERNAME: {{ .Values.secret.pierceflare.values.SERVICE_AUTH_USERNAME | quote }}
  SERVICE_AUTH_PASSWORD: {{ .Values.secret.pierceflare.values.SERVICE_AUTH_PASSWORD | quote }}
{{- end }}