apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpers.fullname" . }}
data:
  PIERCEFLARE_SERVER_URL: {{ .Values.config.env.PIERCEFLARE_SERVER_URL | quote  }}
  PIERCEFLARE_CHECK_INTERVAL: {{ .Values.config.env.PIERCEFLARE_CHECK_INTERVAL | quote  }}
  PIERCEFLARE_DUMMY_UPDATES: {{ .Values.config.env.PIERCEFLARE_DUMMY_UPDATES | quote  }}
  PIERCEFLARE_LOG_LEVEL: {{ .Values.config.env.PIERCEFLARE_LOG_LEVEL | quote  }}
  PIERCEFLARE_SUCCESS_LOG_PERIOD: {{ .Values.config.env.PIERCEFLARE_SUCCESS_LOG_PERIOD | quote  }}
