{{- if not .Values.secret.pierceflare.PIERCEFLARE_API_KEY }}
{{- fail "You must provide .Values.secret.pierceflare.PIERCEFLARE_API_KEY in values.yaml" }}
{{- end }}
{{- if not .Values.secret.pierceflare.PIERCEFLARE_SERVER_URL }}
{{- fail "You must provide .Values.secret.pierceflare.PIERCEFLARE_SERVER_URL in values.yaml" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}
type: Opaque
dataString:
  PIERCEFLARE_API_KEY: {{ .Values.secret.pierceflare.PIERCEFLARE_API_KEY | quote }}
  PIERCEFLARE_SERVER_URL: {{ .Values.secret.pierceflare.PIERCEFLARE_SERVER_URL | quote }}
