services:
  
  #
  # App Stack
  #

  pierceflare:
    image: pierceflare
    build:
      context: ..
      dockerfile: Dockerfile.service
      args:
        - K8S_APP__VERSION=debug-0.0.1-docker
    ports:
      - "80:3000"
    environment:
      SERVICE_AUTH_USERNAME: root
      SERVICE_AUTH_PASSWORD: root
      SERVICE_DATABASE_FILES_PATH: /db
      SERVICE_CLOUDFLARE_AVAILABLE_DOMAINS: ivy.community,qalisa.fr
    volumes:
      - pierceflare-data:/db:rw

#
volumes:
  #
  pierceflare-data:
