services:
  
  #
  # App Stack
  #

  pierceflare:
    image: pierceflare
    build:
      context: ..
      dockerfile: Dockerfile.server
      args:
        - K8S_APP__VERSION=debug-0.0.1-docker
    ports:
      - "80:3000"
    environment:
      SERVICE_AUTH_USERNAME: root
      SERVICE_AUTH_PASSWORD: root
    volumes:
      - pierceflare-data:/foundation/budivy_blobs:rw

#
volumes:
  #
  pierceflare-data:
