services:
  
  #
  # App Stack
  #

  pierceflare:
    image: pierceflare
    build:
      context: ../../service
      args:
        - K8S_APP__VERSION=debug-0.0.1-docker
        - CANONICAL_URL=http://localhost:3000
    ports:
      - "3000:80"
    environment:
      SERVICE_AUTH_USERNAME: root
      SERVICE_AUTH_PASSWORD: root
      SERVICE_DATABASE_FILES_PATH: /db
      #
      K8S_APP__IMAGE_VERSION: pnpm-prod
      K8S_APP__IMAGE_REVISION: 2200000000432122000000004321
    env_file:
      - ../../service/.env
    volumes:
      - pierceflare-data:/db:rw

#
volumes:
  #
  pierceflare-data:
